# Generated by Django 4.1.7 on 2023-03-26 08:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=100)),
                ('car_speed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('car_rpm', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)])),
                ('car_begin_distance', models.PositiveIntegerField(blank=True, default=0)),
                ('car_distance', models.PositiveIntegerField(default=0)),
                ('car_run_time', models.CharField(max_length=100)),
                ('car_tempreture', models.CharField(max_length=100)),
                ('car_fuel_level', models.CharField(max_length=100)),
                ('car_engine_load', models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('car_speed_range', models.FloatField(blank=True, default=0.0)),
                ('car_rpm_range', models.FloatField(blank=True, default=0.0)),
                ('car_distance_range', models.FloatField(blank=True, default=0.0)),
            ],
            options={
                'verbose_name_plural': 'Car',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_image', models.ImageField(upload_to='driver_profile/')),
                ('driver_age', models.PositiveIntegerField(default=18)),
                ('driver_ssn', models.CharField(max_length=30)),
                ('driver_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('driver_action', models.CharField(choices=[('Driving safe', 'Driving safe'), ('Texting right', 'Texting right'), ('Talk with right', 'Talk with right'), ('Texting left', 'Texting left'), ('Talk with left', 'Talk with left'), ('Turn on radio', 'Turn on radio'), ('Drinking', 'Drinking'), ('look behind', 'look behind'), ('hair and makeup', 'hair and makeup'), ('talking passenger', 'talking passenger')], default='Driving safe', max_length=100)),
                ('drive_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcv_app.car')),
            ],
            options={
                'verbose_name_plural': 'Driver',
            },
        ),
        migrations.CreateModel(
            name='Car_Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_sarial', models.CharField(max_length=100)),
                ('diagnostic_error_type', models.CharField(max_length=300)),
                ('diagnostic_for_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcv_app.car')),
            ],
            options={
                'verbose_name_plural': 'Car Diagnostic',
            },
        ),
    ]
