# Generated by Django 4.1.6 on 2023-02-08 11:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_id", models.CharField(max_length=100)),
                (
                    "car_speed",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "car_rpm",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "car_begin_distance",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                ("car_distance", models.PositiveIntegerField(default=0)),
                ("car_run_time", models.CharField(max_length=100)),
                ("car_tempreture", models.CharField(max_length=100)),
                ("car_fuel_level", models.CharField(max_length=100)),
                (
                    "car_engine_load",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("car_speed_range", models.FloatField(blank=True, default=0.0)),
                ("car_rpm_range", models.FloatField(blank=True, default=0.0)),
                ("car_distance_range", models.FloatField(blank=True, default=0.0)),
            ],
            options={"verbose_name_plural": "Car",},
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("driver_name", models.CharField(max_length=100)),
                ("driver_image", models.ImageField(upload_to="driver_profile/")),
                ("driver_age", models.PositiveIntegerField(default=18)),
                ("driver_ssn", models.CharField(max_length=30)),
                (
                    "driver_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "driver_action",
                    models.CharField(
                        choices=[
                            ("Normal driving", "Normal driving"),
                            ("Using phone by right hand", "Using phone by right hand"),
                            ("Make a call by right hand", "Make a call by right hand"),
                            ("Using phone by left hand", "Using phone by left hand"),
                            ("Make a call by left hand", "Make a call by left hand"),
                            ("Opening the radio", "Opening the radio"),
                            ("Drink something", "Drink something"),
                            (
                                "Busy with something behind",
                                "Busy with something behind",
                            ),
                            ("Setting an appearance", "Setting an appearance"),
                            (
                                "Talking with someone in car",
                                "Talking with someone in car",
                            ),
                        ],
                        default="Normal driving",
                        max_length=100,
                    ),
                ),
                (
                    "drive_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mcv.car"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Driver",},
        ),
        migrations.CreateModel(
            name="Car_Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("diagnostic_sarial", models.CharField(max_length=100)),
                ("diagnostic_error_type", models.CharField(max_length=300)),
                (
                    "diagnostic_for_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mcv.car"
                    ),
                ),
            ],
            options={"verbose_name_plural": "Car Diagnostic",},
        ),
    ]
